addSbtPlugin("com.timushev.sbt"  % "sbt-updates"           % "0.3.4")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"         % "0.9.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"         % "1.5.1")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"          % "1.6.0-RC4")
addSbtPlugin("com.github.gseitz" % "sbt-release"           % "1.0.9")
addSbtPlugin("com.lightbend.sbt" % "sbt-multi-release-jar" % "0.1.2")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"               % "1.1.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"          % "2.0")
addSbtPlugin("com.47deg"         % "sbt-microsites"        % "0.8.0")

